# ---------------------------------------------------------
#   File:         PR-To-ADO.yaml
#   Author:       Codey Funston [s222250824@deakin.edu.au]
# 
#   Description:  Creates Azure DevOps task for each PR
#                 in repo based on team member preferences.
# ---------------------------------------------------------

    name: Pull Request Review Setup

    # Runs on every PR in main branch.
    on: [pull_request]
    
    jobs:
      POST-to-Azure-DevOps-API:
        runs-on: windows-latest
    
        steps:
          - name: Checkout Preferences File and Scripts
            uses: actions/checkout@v4
            with:
            #   repository: "Redback-Operations/redback-cyber"
            #   path: "redback-cyber"
              repository: "cfeng44/actions-testing"
              path: "actions-testing"

          - name: Run Select-Reviewer Script
            env:
              REPO: ${{ github.repository }}
            run: |
              $team = ./actions-testing/.github/workflows/scripts/Select-Reviewer.ps1 -Path "./actions-testing/.github/workflows/data/PR_Preferences.json"
              Write-Host $team[2]
    
          - name: Create Task
            env:
              # PAT_TOKEN:   "${{ secrets.AZUREDEVOPSPAT }}"
              PAT_TOKEN: "6vGr5Zqo4827b2HCTrZHB0qRRlNXUtqsk73f0kjwXmCUH88ISKiWJQQJ99ALACAAAAArDC5SAAASAZDOeI7P"
              PR_TITLE:    "PR: ${{ github.event.pull_request.title }}"
              TASK_DESC:   "${{ github.event.pull_request.body}} --> ${{ github.event.pull_request.html_url}}"

            run: |
              ./actions-testing/.github/workflows/scripts/API-Request.ps1
            
              
    
